// Code generated by goyacc -l -o parser.go -v parser.output parser.go.y. DO NOT EDIT.
package filter

import __yyfmt__ "fmt"

import "fmt"

type token struct {
	tok int
	lit interface{}
	pos position
}

type yySymType struct {
	yys     int
	filters Expr
	expr    Expr
	tok     token
}

const tIDENT = 57346
const tTRUE = 57347
const tFALSE = 57348
const tNULL = 57349
const tVALUE = 57350
const tNUMBER = 57351
const tPR = 57352
const tEQ = 57353
const tNE = 57354
const tCO = 57355
const tSW = 57356
const tEW = 57357
const tGT = 57358
const tGE = 57359
const tLT = 57360
const tLE = 57361
const tAND = 57362
const tOR = 57363
const tNOT = 57364
const tLPAREN = 57365
const tRPAREN = 57366
const tLBOXP = 57367
const tRBOXP = 57368
const tSP = 57369
const tDOT = 57370

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"tIDENT",
	"tTRUE",
	"tFALSE",
	"tNULL",
	"tVALUE",
	"tNUMBER",
	"tPR",
	"tEQ",
	"tNE",
	"tCO",
	"tSW",
	"tEW",
	"tGT",
	"tGE",
	"tLT",
	"tLE",
	"tAND",
	"tOR",
	"tNOT",
	"tLPAREN",
	"tRPAREN",
	"tLBOXP",
	"tRBOXP",
	"tSP",
	"tDOT",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

type lexer struct {
	s         *scanner
	recentLit interface{}
	recentPos position
	expr      Expr
	err       chan error
}

func (l *lexer) Lex(lval *yySymType) int {
	tok, lit, pos, err := l.s.Scan()
	if err != nil {
		l.emitError(err)
		return -1
	}
	if tok == tEOF {
		return 0
	}
	lval.tok = token{tok: tok, lit: lit, pos: pos}
	l.recentLit = lit
	l.recentPos = pos
	return tok
}

func (l *lexer) makeError(e interface{}) error {
	switch e := e.(type) {
	case error:
		return fmt.Errorf(`parse error: line %d, column %d: %q: %w`, l.recentPos.Line, l.recentPos.Column, l.recentLit, e)
	default:
		return fmt.Errorf(`parse error: line %d, column %d: %q: %s`, l.recentPos.Line, l.recentPos.Column, l.recentLit, e)
	}
}

// implements yylexer, so it must stay
func (l *lexer) Error(e string) {
	l.emitError(l.makeError(e))
}

func (l *lexer) emitError(err error) {
	select {
	case l.err <- err:
	default:
	}
}

func parse(s *scanner) (Expr, error) {
	l := lexer{s: s, err: make(chan error, 1)}
	if yyParse(&l) != 0 {
		return nil, <-l.err
	}
	return l.expr, nil
}

var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 56

var yyAct = [...]int8{
	3, 9, 10, 11, 12, 13, 14, 15, 16, 17,
	18, 45, 7, 8, 6, 2, 19, 22, 43, 20,
	21, 40, 8, 23, 24, 7, 8, 7, 8, 44,
	34, 41, 5, 4, 33, 39, 25, 32, 42, 7,
	8, 27, 28, 29, 30, 26, 46, 6, 31, 1,
	0, 0, 35, 36, 37, 38,
}

var yyPact = [...]int16{
	10, -1000, 19, -9, 10, -6, -1000, 10, 10, -1000,
	36, 36, 29, 26, 22, 36, 36, 36, 36, 10,
	43, 7, 10, 1, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -8,
	-1000, -1000, 5, -17, -1000, 43, -1000,
}

var yyPgo = [...]int8{
	0, 49, 15, 0, 36,
}

var yyR1 = [...]int8{
	0, 1, 2, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	3, 4, 4, 4, 4, 4,
}

var yyR2 = [...]int8{
	0, 1, 2, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 4, 6, 4, 3, 1,
	1, 1, 1, 1, 1, 1,
}

var yyChk = [...]int16{
	-1000, -1, -2, -3, 23, 22, 4, 20, 21, 10,
	11, 12, 13, 14, 15, 16, 17, 18, 19, 25,
	28, -2, 23, -2, -2, -4, 9, 5, 6, 7,
	8, -4, 8, 8, 8, -4, -4, -4, -4, -2,
	-3, 24, -2, 26, 24, 28, -3,
}

var yyDef = [...]int8{
	0, -2, 1, 19, 0, 0, 20, 0, 0, 2,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 12, 13, 3, 21, 22, 23, 24,
	25, 4, 5, 6, 7, 8, 9, 10, 11, 0,
	18, 14, 0, 17, 15, 0, 16,
}

var yyTok1 = [...]int8{
	1,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.filters = yyDollar[1].expr
			if l, ok := yylex.(*lexer); ok {
				l.expr = yyVAL.filters
			}
		}
	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
		{
			yyVAL.expr = NewPresenceExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string))
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewCompareExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewCompareExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 5:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewRegexExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].tok.lit)
		}
	case 6:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewRegexExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].tok.lit)
		}
	case 7:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewRegexExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].tok.lit)
		}
	case 8:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewCompareExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 9:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewCompareExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewCompareExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewCompareExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewLogExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewLogExpr(yyDollar[1].expr, yyDollar[2].tok.lit.(string), yyDollar[3].expr)
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewParenExpr("", yyDollar[2].expr)
		}
	case 15:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = NewParenExpr(yyDollar[1].tok.lit.(string), yyDollar[3].expr)
		}
	case 16:
		yyDollar = yyS[yypt-6 : yypt+1]
		{
			yyVAL.expr = NewValuePath(yyDollar[1].expr, yyDollar[6].expr, yyDollar[3].expr)
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
		{
			yyVAL.expr = NewValuePath(yyDollar[1].expr, nil, yyDollar[3].expr)
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
		{
			yyVAL.expr = NewValuePath(yyDollar[1].expr, yyDollar[3].expr, nil)
		}
	case 19:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewValuePath(yyDollar[1].expr, nil, nil)
		}
	case 20:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewIdentifierExpr(yyDollar[1].tok.lit.(string))
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewNumberExpr(yyDollar[1].tok.lit.(int))
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewBoolExpr(true)
		}
	case 23:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewBoolExpr(false)
		}
	case 24:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewIdentifierExpr(yyDollar[1].tok.lit.(string))
		}
	case 25:
		yyDollar = yyS[yypt-1 : yypt+1]
		{
			yyVAL.expr = NewAttrValueExpr(yyDollar[1].tok.lit.(string))
		}
	}
	goto yystack /* stack new state and value */
}
