// Generated by "sketch" utility. DO NOT EDIT
package resource

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	"github.com/lestrrat-go/blackmagic"
)

type Error struct {
	mu       sync.RWMutex
	detail   *string
	scimType *ErrorType
	status   *int
	extra    map[string]interface{}
}

// These constants are used when the JSON field name is used.
// Their use is not strictly required, but certain linters
// complain about repeated constants, and therefore internally
// this used throughout
const (
	ErrorDetailKey   = "detail"
	ErrorSCIMTypeKey = "scimType"
	ErrorStatusKey   = "status"
)

// Get retrieves the value associated with a key
func (v *Error) Get(key string, dst interface{}) error {
	v.mu.RLock()
	defer v.mu.RUnlock()
	switch key {
	case ErrorDetailKey:
		if val := v.detail; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	case ErrorSCIMTypeKey:
		if val := v.scimType; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	case ErrorStatusKey:
		if val := v.status; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	default:
		if v.extra != nil {
			val, ok := v.extra[key]
			if ok {
				return blackmagic.AssignIfCompatible(dst, val)
			}
		}
	}
	return fmt.Errorf(`no such key %q`, key)
}

// Set sets the value of the specified field. The name must be a JSON
// field name, not the Go name
func (v *Error) Set(key string, value interface{}) error {
	v.mu.Lock()
	defer v.mu.Unlock()
	switch key {
	case ErrorDetailKey:
		converted, ok := value.(string)
		if !ok {
			return fmt.Errorf(`expected value of type string for field detail, got %T`, value)
		}
		v.detail = &converted
	case ErrorSCIMTypeKey:
		converted, ok := value.(ErrorType)
		if !ok {
			return fmt.Errorf(`expected value of type ErrorType for field scimType, got %T`, value)
		}
		v.scimType = &converted
	case ErrorStatusKey:
		converted, ok := value.(int)
		if !ok {
			return fmt.Errorf(`expected value of type int for field status, got %T`, value)
		}
		v.status = &converted
	default:
		if v.extra == nil {
			v.extra = make(map[string]interface{})
		}
		v.extra[key] = value
	}
	return nil
}
func (v *Error) HasDetail() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.detail != nil
}

func (v *Error) HasSCIMType() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.scimType != nil
}

func (v *Error) HasStatus() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.status != nil
}

func (v *Error) Detail() string {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.detail; val != nil {
		return *val
	}
	return ""
}

func (v *Error) SCIMType() ErrorType {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.scimType; val != nil {
		return *val
	}
	return ""
}

func (v *Error) Status() int {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.status; val != nil {
		return *val
	}
	return 0
}

// Remove removes the value associated with a key
func (v *Error) Remove(key string) error {
	v.mu.Lock()
	defer v.mu.Unlock()

	switch key {
	case ErrorDetailKey:
		v.detail = nil
	case ErrorSCIMTypeKey:
		v.scimType = nil
	case ErrorStatusKey:
		v.status = nil
	default:
		delete(v.extra, key)
	}

	return nil
}

func (v *Error) makePairs() []*fieldPair {
	pairs := make([]*fieldPair, 0, 3)
	if val := v.detail; val != nil {
		pairs = append(pairs, &fieldPair{Name: ErrorDetailKey, Value: *val})
	}
	if val := v.scimType; val != nil {
		pairs = append(pairs, &fieldPair{Name: ErrorSCIMTypeKey, Value: *val})
	}
	if val := v.status; val != nil {
		pairs = append(pairs, &fieldPair{Name: ErrorStatusKey, Value: *val})
	}

	for key, val := range v.extra {
		pairs = append(pairs, &fieldPair{Name: key, Value: val})
	}

	sort.Slice(pairs, func(i, j int) bool {
		return pairs[i].Name < pairs[j].Name
	})
	return pairs
}

// MarshalJSON serializes Error into JSON.
// All pre-declared fields are included as long as a value is
// assigned to them, as well as all extra fields. All of these
// fields are sorted in alphabetical order.
func (v *Error) MarshalJSON() ([]byte, error) {
	pairs := v.makePairs()

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	buf.WriteByte('{')
	for i, pair := range pairs {
		if i > 0 {
			buf.WriteByte(',')
		}
		if err := enc.Encode(pair.Name); err != nil {
			return nil, fmt.Errorf(`failed to encode map key name: %w`, err)
		}
		buf.WriteByte(':')
		if err := enc.Encode(pair.Value); err != nil {
			return nil, fmt.Errorf(`failed to encode map value for %q: %w`, pair.Name, err)
		}
	}
	buf.WriteByte('}')
	return buf.Bytes(), nil
}

// UnmarshalJSON deserializes a piece of JSON data into Error.
//
// Pre-defined fields must be deserializable via "encoding/json" to their
// respective Go types, otherwise an error is returned.
//
// Extra fields are stored in a special "extra" storage, which can only
// be accessed via `Get()` and `Set()` methods.
func (v *Error) UnmarshalJSON(data []byte) error {
	v.mu.Lock()
	defer v.mu.Unlock()
	v.detail = nil
	v.scimType = nil
	v.status = nil

	dec := json.NewDecoder(bytes.NewReader(data))
	var extra map[string]interface{}

LOOP:
	for {
		tok, err := dec.Token()
		if err != nil {
			return fmt.Errorf(`error reading JSON token: %w`, err)
		}
		switch tok := tok.(type) {
		case json.Delim:
			if tok == '}' { // end of object
				break LOOP
			}
			// we should only get into this clause at the very beginning, and just once
			if tok != '{' {
				return fmt.Errorf(`expected '{', but got '%c'`, tok)
			}
		case string:
			switch tok {
			case ErrorDetailKey:
				var val string
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, ErrorDetailKey, err)
				}
				v.detail = &val
			case ErrorSCIMTypeKey:
				var val ErrorType
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, ErrorSCIMTypeKey, err)
				}
				v.scimType = &val
			case ErrorStatusKey:
				var val int
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, ErrorStatusKey, err)
				}
				v.status = &val
			default:
				var val interface{}
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, tok, err)
				}
				if extra == nil {
					extra = make(map[string]interface{})
				}
				extra[tok] = val
			}
		}
	}

	if extra != nil {
		v.extra = extra
	}
	return nil
}

type ErrorBuilder struct {
	mu     sync.Mutex
	err    error
	once   sync.Once
	object *Error
}

// NewErrorBuilder creates a new ErrorBuilder instance.
// ErrorBuilder is safe to be used uninitialized as well.
func NewErrorBuilder() *ErrorBuilder {
	return &ErrorBuilder{}
}

func (b *ErrorBuilder) initialize() {
	b.err = nil
	b.object = &Error{}
}
func (b *ErrorBuilder) Detail(in string) *ErrorBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(ErrorDetailKey, in); err != nil {
		b.err = err
	}
	return b
}
func (b *ErrorBuilder) SCIMType(in ErrorType) *ErrorBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(ErrorSCIMTypeKey, in); err != nil {
		b.err = err
	}
	return b
}
func (b *ErrorBuilder) Status(in int) *ErrorBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(ErrorStatusKey, in); err != nil {
		b.err = err
	}
	return b
}

func (b *ErrorBuilder) Build() (*Error, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	if err := b.err; err != nil {
		return nil, err
	}
	obj := b.object
	b.once = sync.Once{}
	b.once.Do(b.initialize)
	return obj, nil
}

func (b *ErrorBuilder) MustBuild() *Error {
	object, err := b.Build()
	if err != nil {
		panic(err)
	}
	return object
}

func (b *ErrorBuilder) From(in *Error) *ErrorBuilder {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.once.Do(b.initialize)
	b.object = in.Clone()
	return b
}

func (v *Error) Clone() *Error {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return &Error{
		detail:   v.detail,
		scimType: v.scimType,
		status:   v.status,
	}
}

func (v *Error) AsMap(dst map[string]interface{}) error {
	for _, pair := range v.makePairs() {
		dst[pair.Name] = pair.Value
	}
	return nil
}

// GetExtension takes into account extension uri, and fetches
// the specified attribute from the extension object
func (v *Error) GetExtension(name, uri string, dst interface{}) error {
	if uri == "" {
		return v.Get(name, dst)
	}
	var ext interface{}
	if err := v.Get(uri, &ext); err != nil {
		return fmt.Errorf(`failed to fetch extension %q: %w`, uri, err)
	}

	getter, ok := ext.(interface {
		Get(string, interface{}) error
	})
	if !ok {
		return fmt.Errorf(`extension does not implement Get(string, interface{}) error`)
	}
	return getter.Get(name, dst)
}

func (b *Builder) Error() *ErrorBuilder {
	return &ErrorBuilder{}
}
