// Generated by "sketch" utility. DO NOT EDIT
package resource

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"sync"

	"github.com/lestrrat-go/blackmagic"
)

func init() {
	Register("Names", "", Names{})
	RegisterBuilder("Names", "", NamesBuilder{})
}

type Names struct {
	mu              sync.RWMutex
	familyName      *string
	formatted       *string
	givenName       *string
	honorificPrefix *string
	honorificSuffix *string
	middleName      *string
	extra           map[string]interface{}
}

// These constants are used when the JSON field name is used.
// Their use is not strictly required, but certain linters
// complain about repeated constants, and therefore internally
// this used throughout
const (
	NamesFamilyNameKey      = "familyName"
	NamesFormattedKey       = "formatted"
	NamesGivenNameKey       = "givenName"
	NamesHonorificPrefixKey = "honorificPrefix"
	NamesHonorificSuffixKey = "honorificSuffix"
	NamesMiddleNameKey      = "middleName"
)

// Get retrieves the value associated with a key
func (v *Names) Get(key string, dst interface{}) error {
	v.mu.RLock()
	defer v.mu.RUnlock()
	switch key {
	case NamesFamilyNameKey:
		if val := v.familyName; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	case NamesFormattedKey:
		if val := v.formatted; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	case NamesGivenNameKey:
		if val := v.givenName; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	case NamesHonorificPrefixKey:
		if val := v.honorificPrefix; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	case NamesHonorificSuffixKey:
		if val := v.honorificSuffix; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	case NamesMiddleNameKey:
		if val := v.middleName; val != nil {
			return blackmagic.AssignIfCompatible(dst, *val)
		}
	default:
		if v.extra != nil {
			val, ok := v.extra[key]
			if ok {
				return blackmagic.AssignIfCompatible(dst, val)
			}
		}
	}
	return fmt.Errorf(`no such key %q`, key)
}

// Set sets the value of the specified field. The name must be a JSON
// field name, not the Go name
func (v *Names) Set(key string, value interface{}) error {
	v.mu.Lock()
	defer v.mu.Unlock()
	switch key {
	case NamesFamilyNameKey:
		converted, ok := value.(string)
		if !ok {
			return fmt.Errorf(`expected value of type string for field familyName, got %T`, value)
		}
		v.familyName = &converted
	case NamesFormattedKey:
		converted, ok := value.(string)
		if !ok {
			return fmt.Errorf(`expected value of type string for field formatted, got %T`, value)
		}
		v.formatted = &converted
	case NamesGivenNameKey:
		converted, ok := value.(string)
		if !ok {
			return fmt.Errorf(`expected value of type string for field givenName, got %T`, value)
		}
		v.givenName = &converted
	case NamesHonorificPrefixKey:
		converted, ok := value.(string)
		if !ok {
			return fmt.Errorf(`expected value of type string for field honorificPrefix, got %T`, value)
		}
		v.honorificPrefix = &converted
	case NamesHonorificSuffixKey:
		converted, ok := value.(string)
		if !ok {
			return fmt.Errorf(`expected value of type string for field honorificSuffix, got %T`, value)
		}
		v.honorificSuffix = &converted
	case NamesMiddleNameKey:
		converted, ok := value.(string)
		if !ok {
			return fmt.Errorf(`expected value of type string for field middleName, got %T`, value)
		}
		v.middleName = &converted
	default:
		if v.extra == nil {
			v.extra = make(map[string]interface{})
		}
		v.extra[key] = value
	}
	return nil
}
func (v *Names) HasFamilyName() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.familyName != nil
}

func (v *Names) HasFormatted() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.formatted != nil
}

func (v *Names) HasGivenName() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.givenName != nil
}

func (v *Names) HasHonorificPrefix() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.honorificPrefix != nil
}

func (v *Names) HasHonorificSuffix() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.honorificSuffix != nil
}

func (v *Names) HasMiddleName() bool {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return v.middleName != nil
}

func (v *Names) FamilyName() string {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.familyName; val != nil {
		return *val
	}
	return ""
}

func (v *Names) Formatted() string {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.formatted; val != nil {
		return *val
	}
	return ""
}

func (v *Names) GivenName() string {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.givenName; val != nil {
		return *val
	}
	return ""
}

func (v *Names) HonorificPrefix() string {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.honorificPrefix; val != nil {
		return *val
	}
	return ""
}

func (v *Names) HonorificSuffix() string {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.honorificSuffix; val != nil {
		return *val
	}
	return ""
}

func (v *Names) MiddleName() string {
	v.mu.RLock()
	defer v.mu.RUnlock()
	if val := v.middleName; val != nil {
		return *val
	}
	return ""
}

// Remove removes the value associated with a key
func (v *Names) Remove(key string) error {
	v.mu.Lock()
	defer v.mu.Unlock()

	switch key {
	case NamesFamilyNameKey:
		v.familyName = nil
	case NamesFormattedKey:
		v.formatted = nil
	case NamesGivenNameKey:
		v.givenName = nil
	case NamesHonorificPrefixKey:
		v.honorificPrefix = nil
	case NamesHonorificSuffixKey:
		v.honorificSuffix = nil
	case NamesMiddleNameKey:
		v.middleName = nil
	default:
		delete(v.extra, key)
	}

	return nil
}

func (v *Names) makePairs() []*fieldPair {
	pairs := make([]*fieldPair, 0, 6)
	if val := v.familyName; val != nil {
		pairs = append(pairs, &fieldPair{Name: NamesFamilyNameKey, Value: *val})
	}
	if val := v.formatted; val != nil {
		pairs = append(pairs, &fieldPair{Name: NamesFormattedKey, Value: *val})
	}
	if val := v.givenName; val != nil {
		pairs = append(pairs, &fieldPair{Name: NamesGivenNameKey, Value: *val})
	}
	if val := v.honorificPrefix; val != nil {
		pairs = append(pairs, &fieldPair{Name: NamesHonorificPrefixKey, Value: *val})
	}
	if val := v.honorificSuffix; val != nil {
		pairs = append(pairs, &fieldPair{Name: NamesHonorificSuffixKey, Value: *val})
	}
	if val := v.middleName; val != nil {
		pairs = append(pairs, &fieldPair{Name: NamesMiddleNameKey, Value: *val})
	}

	for key, val := range v.extra {
		pairs = append(pairs, &fieldPair{Name: key, Value: val})
	}

	sort.Slice(pairs, func(i, j int) bool {
		return pairs[i].Name < pairs[j].Name
	})
	return pairs
}

// MarshalJSON serializes Names into JSON.
// All pre-declared fields are included as long as a value is
// assigned to them, as well as all extra fields. All of these
// fields are sorted in alphabetical order.
func (v *Names) MarshalJSON() ([]byte, error) {
	pairs := v.makePairs()

	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	buf.WriteByte('{')
	for i, pair := range pairs {
		if i > 0 {
			buf.WriteByte(',')
		}
		if err := enc.Encode(pair.Name); err != nil {
			return nil, fmt.Errorf(`failed to encode map key name: %w`, err)
		}
		buf.WriteByte(':')
		if err := enc.Encode(pair.Value); err != nil {
			return nil, fmt.Errorf(`failed to encode map value for %q: %w`, pair.Name, err)
		}
	}
	buf.WriteByte('}')
	return buf.Bytes(), nil
}

// UnmarshalJSON deserializes a piece of JSON data into Names.
//
// Pre-defined fields must be deserializable via "encoding/json" to their
// respective Go types, otherwise an error is returned.
//
// Extra fields are stored in a special "extra" storage, which can only
// be accessed via `Get()` and `Set()` methods.
func (v *Names) UnmarshalJSON(data []byte) error {
	v.mu.Lock()
	defer v.mu.Unlock()
	v.familyName = nil
	v.formatted = nil
	v.givenName = nil
	v.honorificPrefix = nil
	v.honorificSuffix = nil
	v.middleName = nil

	dec := json.NewDecoder(bytes.NewReader(data))
	var extra map[string]interface{}

LOOP:
	for {
		tok, err := dec.Token()
		if err != nil {
			return fmt.Errorf(`error reading JSON token: %w`, err)
		}
		switch tok := tok.(type) {
		case json.Delim:
			if tok == '}' { // end of object
				break LOOP
			}
			// we should only get into this clause at the very beginning, and just once
			if tok != '{' {
				return fmt.Errorf(`expected '{', but got '%c'`, tok)
			}
		case string:
			switch tok {
			case NamesFamilyNameKey:
				var val string
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, NamesFamilyNameKey, err)
				}
				v.familyName = &val
			case NamesFormattedKey:
				var val string
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, NamesFormattedKey, err)
				}
				v.formatted = &val
			case NamesGivenNameKey:
				var val string
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, NamesGivenNameKey, err)
				}
				v.givenName = &val
			case NamesHonorificPrefixKey:
				var val string
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, NamesHonorificPrefixKey, err)
				}
				v.honorificPrefix = &val
			case NamesHonorificSuffixKey:
				var val string
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, NamesHonorificSuffixKey, err)
				}
				v.honorificSuffix = &val
			case NamesMiddleNameKey:
				var val string
				if err := dec.Decode(&val); err != nil {
					return fmt.Errorf(`failed to decode value for %q: %w`, NamesMiddleNameKey, err)
				}
				v.middleName = &val
			default:
				var val interface{}
				if err := extraFieldsDecoder(tok, dec, &val); err != nil {
					return err
				}
				if extra == nil {
					extra = make(map[string]interface{})
				}
				extra[tok] = val
			}
		}
	}

	if extra != nil {
		v.extra = extra
	}
	return nil
}

type NamesBuilder struct {
	mu     sync.Mutex
	err    error
	once   sync.Once
	object *Names
}

// NewNamesBuilder creates a new NamesBuilder instance.
// NamesBuilder is safe to be used uninitialized as well.
func NewNamesBuilder() *NamesBuilder {
	return &NamesBuilder{}
}

func (b *NamesBuilder) initialize() {
	b.err = nil
	b.object = &Names{}
}
func (b *NamesBuilder) FamilyName(in string) *NamesBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(NamesFamilyNameKey, in); err != nil {
		b.err = err
	}
	return b
}
func (b *NamesBuilder) Formatted(in string) *NamesBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(NamesFormattedKey, in); err != nil {
		b.err = err
	}
	return b
}
func (b *NamesBuilder) GivenName(in string) *NamesBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(NamesGivenNameKey, in); err != nil {
		b.err = err
	}
	return b
}
func (b *NamesBuilder) HonorificPrefix(in string) *NamesBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(NamesHonorificPrefixKey, in); err != nil {
		b.err = err
	}
	return b
}
func (b *NamesBuilder) HonorificSuffix(in string) *NamesBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(NamesHonorificSuffixKey, in); err != nil {
		b.err = err
	}
	return b
}
func (b *NamesBuilder) MiddleName(in string) *NamesBuilder {
	b.once.Do(b.initialize)
	b.mu.Lock()
	defer b.mu.Unlock()
	if b.err != nil {
		return b
	}

	if err := b.object.Set(NamesMiddleNameKey, in); err != nil {
		b.err = err
	}
	return b
}

func (b *NamesBuilder) Build() (*Names, error) {
	b.mu.Lock()
	defer b.mu.Unlock()
	if err := b.err; err != nil {
		return nil, err
	}
	obj := b.object
	b.once = sync.Once{}
	b.once.Do(b.initialize)
	return obj, nil
}

func (b *NamesBuilder) MustBuild() *Names {
	object, err := b.Build()
	if err != nil {
		panic(err)
	}
	return object
}

func (b *NamesBuilder) From(in *Names) *NamesBuilder {
	b.mu.Lock()
	defer b.mu.Unlock()
	b.once.Do(b.initialize)
	b.object = in.Clone()
	return b
}

func (v *Names) Clone() *Names {
	v.mu.RLock()
	defer v.mu.RUnlock()
	return &Names{
		familyName:      v.familyName,
		formatted:       v.formatted,
		givenName:       v.givenName,
		honorificPrefix: v.honorificPrefix,
		honorificSuffix: v.honorificSuffix,
		middleName:      v.middleName,
	}
}

func (v *Names) AsMap(dst map[string]interface{}) error {
	for _, pair := range v.makePairs() {
		dst[pair.Name] = pair.Value
	}
	return nil
}

// GetExtension takes into account extension uri, and fetches
// the specified attribute from the extension object
func (v *Names) GetExtension(name, uri string, dst interface{}) error {
	if uri == "" {
		return v.Get(name, dst)
	}
	var ext interface{}
	if err := v.Get(uri, &ext); err != nil {
		return fmt.Errorf(`failed to fetch extension %q: %w`, uri, err)
	}

	getter, ok := ext.(interface {
		Get(string, interface{}) error
	})
	if !ok {
		return fmt.Errorf(`extension does not implement Get(string, interface{}) error`)
	}
	return getter.Get(name, dst)
}

func (b *Builder) Names() *NamesBuilder {
	return &NamesBuilder{}
}
