// This file is auto-generated by tools/cmd/genoptions/main.go. DO NOT EDIT

package resource

import (
	"github.com/lestrrat-go/option"
)

type Option = option.Interface

// GetOption describes an Option that can be passed to `Get()`.
type GetOption interface {
	Option
	getOption()
}

type getOption struct {
	Option
}

func (*getOption) getOption() {}

type identExtension struct{}

func (identExtension) String() string {
	return "WithExtension"
}

// WithEstension specifies the extension name to be used.
func WithExtension(v string) GetOption {
	return &getOption{option.New(identExtension{}, v)}
}
