name: Auto-Doc
on:
  pull_request:
    types:
      - closed

jobs:
  autodoc:
    runs-on: ubuntu-latest
    name: "Run commands to generate documentation"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Process markdown files
        run: |
          find . -name '*.md' | xargs perl tools/autodoc.pl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
